UPDATE app_settings
   SET value_json = '"15m"'
 WHERE key = 'reminders.defaultSnooze' AND updated_at = 0;

INSERT OR IGNORE INTO app_settings (key, value_json, updated_at) VALUES
    ('focus.quickDurations', '[25,50,75]', 0),
    ('focus.showCompletionNote', 'true', 0),
    ('focus.requireCompletionNote', 'true', 0),
    ('notifications.focusSound', 'true', 0),
    ('notifications.reminderSound', 'false', 0),
    ('focus.startBehavior', '"default"', 0),
    ('focus.rememberLastDuration', 'false', 0),
    ('focus.lastDuration', '25', 0),
    ('interruptions.reasonPrompt', '"resume"', 0),
    ('reminders.snoozeOptions', '["5m","15m","30m","1h","tomorrow"]', 0),
    ('reminders.openBehavior', '"popup"', 0),
    ('reminders.dismissOnTerminalTask', 'true', 0),
    ('reports.includeCompleted', 'true', 0),
    ('reports.includeWorkInProgress', 'true', 0),
    ('reports.defaultPeriod', '"today"', 0),
    ('reports.detail', '"concise"', 0),
    ('desktop.launchAtStartup', 'false', 0),
    ('desktop.closeBehavior', '"tray"', 0),
    ('desktop.minimizeToTray', 'false', 0),
    ('desktop.showTrayIcon', 'true', 0),
    ('desktop.keepTimersInTray', 'true', 0),
    ('desktop.keepRemindersInTray', 'true', 0),
    ('desktop.restoreWindowState', 'true', 0),
    ('desktop.startMinimized', 'false', 0),
    ('shortcuts.enabled', 'true', 0),
    ('tasks.defaultStatus', '"todo"', 0),
    ('tasks.startFocusAfterCreate', 'false', 0),
    ('tasks.confirmCancel', 'true', 0),
    ('tasks.confirmDelete', 'true', 0),
    ('tasks.showCompletedToday', 'true', 0),
    ('tasks.defaultSort', '"recently-worked"', 0),
    ('timeline.defaultFilter', '"all"', 0),
    ('timeline.showNotesInline', 'true', 0),
    ('timeline.collapseLongNotes', 'true', 0),
    ('timeline.confirmDelete', 'true', 0);
