export const defaultSettings = {
  "appearance.accent": "#2388FF",
  "appearance.background": "#050B14",
  "focus.defaultDuration": 25,
  "focus.longDuration": 50,
  "focus.quickDurations": [25, 50, 75],
  "focus.showCompletionNote": true,
  "focus.requireCompletionNote": true,
  "focus.startBehavior": "default",
  "focus.rememberLastDuration": false,
  "focus.lastDuration": 25,
  "focus.breakDuration": 5,
  "notifications.focusComplete": true,
  "notifications.reminders": true,
  "notifications.focusSound": true,
  "notifications.breakSound": true,
  "notifications.focusSoundStyle": "chime",
  "notifications.breakSoundStyle": "gentle",
  "notifications.reminderSound": false,
  "reminders.defaultSnooze": "15m",
  "reminders.snoozeOptions": ["5m", "15m", "30m", "1h", "tomorrow"],
  "reminders.openBehavior": "popup",
  "reminders.dismissOnTerminalTask": true,
  "interruptions.reasonPrompt": "resume",
  "reports.includeTotalFocusTime": true,
  "reports.includeTimePerTask": true,
  "reports.includeCompleted": true,
  "reports.includeWorkInProgress": true,
  "reports.includeInterruptions": false,
  "reports.includeBreaks": false,
  "reports.defaultPeriod": "today",
  "reports.detail": "concise",
  "desktop.launchAtStartup": false,
  "desktop.closeBehavior": "tray",
  "desktop.minimizeToTray": false,
  "desktop.showTrayIcon": true,
  "desktop.keepTimersInTray": true,
  "desktop.keepRemindersInTray": true,
  "desktop.restoreWindowState": true,
  "desktop.startMinimized": false,
  "shortcuts.enabled": true,
  "tasks.defaultStatus": "todo",
  "tasks.startFocusAfterCreate": false,
  "tasks.confirmCancel": true,
  "tasks.confirmDelete": true,
  "tasks.showCompletedToday": true,
  "tasks.defaultSort": "recently-worked",
  "timeline.defaultFilter": "all",
  "timeline.showNotesInline": true,
  "timeline.collapseLongNotes": true,
  "timeline.confirmDelete": true,
  "backup.lastAt": null as number | null,
} as const;

export type SettingKey = keyof typeof defaultSettings;
type Widen<T> = T extends string ? string : T extends number ? number : T extends boolean ? boolean : T extends readonly (infer Item)[] ? Widen<Item>[] : T;
export type SettingsState = { [K in SettingKey]: Widen<typeof defaultSettings[K]> };
